"""Create Game Model

Revision ID: 46b705bbba67
Revises: e9e54c5e3e3d
Create Date: 2023-12-06 16:10:26.213293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b705bbba67'
down_revision = 'e9e54c5e3e3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
